name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  
  build: 
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image 
        run: docker build -t arland99/portfolio .

      - name: push image
        run: |
            docker login -u arland99 -p ${{secrets.REGISTRY_PASS}}
            docker push arland99/portfolio

